### ISSUE TITLE
Empty Array

### ISSUE THREAD

**Issue by AuroPick** [Jakeisbored/corona-tracker#1]
I was trying how it works. I tried the example you gave us but it gave me an empty array.
![corona](https://user-images.githubusercontent.com/53499802/76792425-18802380-67d4-11ea-80d6-1a3aea67adb8.png)

**Comment by Jakeisbored** [comment]
Edit : 
Implemented a patch to fix this , please update to the latest version to fix this problem.
Also , thanks for the report

**Comment by Jakeisbored** [comment]
Edit : implemented a patch to fix this , please update to the latest version to fix this problem.
Also , thanks for the report

**Comment by Jakeisbored** [comment]
Edit : implemented a patch to fix this , please update to the latest version to fix this problem.
Also , thanks for the report
